# Generated by Django 5.1.3 on 2024-11-27 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=700)),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(blank=True, default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['publication_datetime'],
                'permissions': [('can_administer_messages', 'Can administer all messages')],
                'indexes': [models.Index(fields=['publication_datetime'], name='chats_messa_publica_8302c4_idx'), models.Index(fields=['is_read'], name='chats_messa_is_read_0e2e50_idx'), models.Index(fields=['sender', 'recipient'], name='chats_messa_sender__03615a_idx')],
            },
        ),
    ]
