# Generated by Django 5.1.3 on 2024-11-27 19:54

import MessangerplusApp.posts.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='posts/', validators=[MessangerplusApp.posts.validators.validate_picture_size])),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publication_datetime'],
                'permissions': [('can_administer_posts', 'Can administer all posts')],
                'indexes': [models.Index(fields=['publication_datetime'], name='posts_post_publica_366c4f_idx')],
            },
        ),
    ]
